language: node_js
node_js:
  - "5.0.0"
after_success:
  - npm run bundle
  - npm run build-doc
notifications:
  email: false
addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-lang-finnish
deploy:
  provider: heroku
  skip_cleanup: true
  app: peaceful-scrubland-8625
  api_key:
    secure: sqludqY++LKxCAInoms6GjNAVAdw3bFa+2UCsYS4d3oNiCHQkDkyLh9tb3JCDEXGC7DwnWPZ22KQLrhuuCzDqnOy0DaIPuW4qvh8EJ5fmkVgrVy+S2odKpTzZ8lwhSGbI7R7bg6y0HVmaRho/paEl03UUVdri3IQuuLVfqNRk6A2XJQoFei2iAjK77J6EQMNcyXhLHYP47aj0SV0CQoK5OjcLmPWESUQb+IcG81RXa3t1re6iahAJmbNoGNuVDNBLHNOMLwdvq2rccYQe5lVxVhTPdDrjs2fmAHa3v0EK6LE0+yaMuMbiR1U1SwZ6rU4WgHPuPfY8Z9SVRr1wRdpoAxMHfQ+64iz5+WKY4w9DUQYmAQHE4ZOXL87DzIoWdFklvxkIa8GaQxCTaK+kfO6SnIguktOCqRdZmBh5SLF06WqQV82rB7sTgQGXJdk+s3Gxvmvhob5hd8D+TWBwvNKw0JDQ+U+kla+JF7ZnCCKepc4lIXwm3TpeohZXL2Ooqmu7Ae1/fISx6AyEiMY5wAdaKeX1N3DTyRUDtrokNV160r+7ulV7W84Ff6ldVyC3V2PfR0An82p8h1C+yED9tBgECqIa8IIPsL6k8hflBnTMtH0KINcoWCuS+ZrSNCpWnlZDYM2C3Req9f+YKVGhwZ3ji2Q2pxu30v5qGxAGgSAi+8=
