BEGIN;
  DROP TABLE IF EXISTS additionalDrinkNames;
  DROP TABLE IF EXISTS drinkIngredients;
  DROP TABLE IF EXISTS drinks;
  DROP TABLE IF EXISTS ingredients;
  DROP TABLE IF EXISTS drinkTypes;
  DROP TABLE IF EXISTS users;
COMMIT;
